default: &default
  adapter: postgis
  encoding: unicode
  pool: 200
  timeout: 5000
  database: realsmart
  schema_search_path: "geom,demog,public"

development:
  <<: *default


production:
  adapter: postgis
  host: realsmart.cn0idi7naiuf.us-east-1.rds.amazonaws.com
  database: realsmart
  password: <%= Rails.application.secrets.database_password %>